version: '3.5'

services:
  etcd:
    image: quay.io/coreos/etcd:latest
    command: etcd -listen-peer-urls=http://127.0.0.1:2380 -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379,http://0.0.0.0:4001 -initial-advertise-peer-urls=http://127.0.0.1:2380 --initial-cluster default=http://127.0.0.1:2380
    ports:
      - "2379:2379"
      - "2380:2380"
      - "4001:4001"
    networks:
      - milvus

  pulsar:
    image: apachepulsar/pulsar:latest
    command: bin/pulsar standalone
    ports:
      - "6650:6650"
      - "18080:8080"
    networks:
      - milvus

  minio:
    image: minio/minio:RELEASE.2020-12-03T00-03-10Z
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    command: minio server /minio_data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - milvus

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"
    networks:
      - milvus

networks:
  milvus:

#  pd0:
#    image: pingcap/pd:latest
#    network_mode: "host"
#    ports:
#      - "2379:2379"
#      - "2380:2380"
#    volumes:
#      - /tmp/config/pd.toml:/pd.toml:ro
#      - /tmp/data:/data
#      - /tmp/logs:/logs
#      - /etc/localtime:/etc/localtime:ro
#    command:
#      - --name=pd0
#      - --client-urls=http://0.0.0.0:2379
#      - --peer-urls=http://0.0.0.0:2380
#      - --advertise-client-urls=http://127.0.0.1:2379
#      - --advertise-peer-urls=http://127.0.0.1:2380
#      - --initial-cluster=pd0=http://127.0.0.1:2380
#      - --data-dir=/data/pd0
#      - --log-file=/logs/pd0.log
#    restart: on-failure
#
#  tikv0:
#    network_mode: "host"
#    image: pingcap/tikv:latest
#    ports:
#      - "20160:20160"
#    volumes:
#      - /tmp/config/tikv.toml:/tikv.toml:ro
#      - /tmp/data:/data
#      - /tmp/logs:/logs
#      - /etc/localtime:/etc/localtime:ro
#    command:
#      - --addr=0.0.0.0:20160
#      - --advertise-addr=127.0.0.1:20160
#      - --data-dir=/data/tikv0
#      - --pd=127.0.0.1:2379
#      - --log-file=/logs/tikv0.log
#    depends_on:
#      - "pd0"
#    restart: on-failure
